// import styles from '../styles/Home.module.css'
import styles from '../styles/layout.module.css'
import Head from 'next/head'



import Cabecalho_Cardapio from './layout/Cabecalho_Cardapio';

import PaginaCardapio from './Arranjos/PaginaCardapio';
import NavCardapio from './Arranjos/NavCardapio';
import Rodape from './layout/Rodape';
import { useRef } from 'react';
import { useState } from 'react';
export default function Cardapio({ conteudo,mudaRenderiza }) {


  let posicaoElemento= [];
  for (let i = 0; i < 5; i++) {
    posicaoElemento[i]= useRef('nulo');
    
  }
 
 
  // const myRef2 = useRef(null)
  // const myRef3 = useRef(null)
  // const myRef4 = useRef(null)
  // const myRef = [useRef(null),useRef(null),useRef(null),useRef(null),]


  const [estaAtivo,setAtivo] = useState(null)
  const poeAtivo = (indice) =>{
      if (indice==indice){
          // setInativo(indice)
          
      }
      setAtivo(indice)
      console.log('ativandooo')
  }

  const posiciona =(i) => {
    posicaoElemento[i].current.scrollIntoView({behavior:"smooth",display:'relative',top:'20%'})    
    console.log(posicaoElemento)
  }

  // const posiciona2 =() => {
  //   // posicaoElemento2.current.scrollIntoView()    
  //   console.log(posicaoElemento2)
  // }

    return (

<body className={styles.estrutura}>
      <Head>
        <title>Quick Galetos</title>
        {/* <meta name="Sítio do café" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, cardápio galeto opções pratos" />
      </Head>


      <Cabecalho_Cardapio funcao={mudaRenderiza}/>
    
      
      <div  className={styles.corpo_cardapio} >

      <NavCardapio  funcao={posiciona}/>
     {/* automatizar titulo! */}
      <PaginaCardapio  ref={posicaoElemento[0]} key={1} conteudo={conteudo}  pagina={1} posicao_a={1} posicao_b={11} titulo='Carnes' estaAtivo={estaAtivo} poeAtivo={poeAtivo} />
      <PaginaCardapio  ref={posicaoElemento[1]} key={2} conteudo={conteudo}  pagina={1} posicao_a={12} posicao_b={29} titulo='Vegetais' estaAtivo={estaAtivo} poeAtivo={poeAtivo} />
      <PaginaCardapio  ref={posicaoElemento[2]} key={3} conteudo={conteudo}  pagina={3} posicao_a={30} posicao_b={44} titulo='Saladas' estaAtivo={estaAtivo} poeAtivo={poeAtivo} />
      <PaginaCardapio  ref={posicaoElemento[3]} key={4} conteudo={conteudo}  pagina={4} posicao_a={45} posicao_b={56} titulo='Bebidas' estaAtivo={estaAtivo} poeAtivo={poeAtivo} />
      <PaginaCardapio  ref={posicaoElemento[4]} key={5} conteudo={conteudo}  pagina={5} posicao_a={57} posicao_b={68} titulo='Cervejas' estaAtivo={estaAtivo} poeAtivo={poeAtivo} />
      {/* <PaginaCardapio conteudo={conteudo} pagina={2}  /> */}
      </div >
        
      {/* <IMGFundo /> */}
      <Rodape />


    </body>



    //    {/* <Conteudo_Cardapio Cardapio={conteudo.Cardapio} posicao={0} /> */}

    );
  };
  
