// import styles from '../styles/Home.module.css'
import styles from '../styles/layout.module.css'
import Head from 'next/head'



import Cabecalho from './layout/Cabecalho';

import PaginaCardapio from './Arranjos/PaginaCardapio';
import NavCardapio from './Arranjos/NavCardapio';
import Rodape from './layout/Rodape';
import { useRef } from 'react';
import { useState } from 'react';
export default function Cardapio({ conteudo,mudaRenderiza }) {
  let posicaoElemento = useRef('nulo')
  // const posicaoElemento = useRef(null)
  // const myRef2 = useRef(null)
  // const myRef3 = useRef(null)
  // const myRef4 = useRef(null)
  // const myRef = [useRef(null),useRef(null),useRef(null),useRef(null),]

  const posiciona =() => {
    // posicaoElemento.current.focus()    
    console.log(posicaoElemento)
  }

  // run this function from an event handler or an effect to execute scroll 

  // const [renderiza, setRenderiza] = useState('primeiro')
  // renderizaDimensao = 


  // const myRef = useRef(null)

  //  const executeScroll = () => myRef.current.scrollIntoView()    
  //  // run this function from an event handler or an effect to execute scroll 

  //  return (
  //     <> 
  //        <div ref={myRef}>Element to scroll to</div> 
  //        <button onClick={executeScroll}> Click to scroll </button> 
  //     </>
  const [estaAtivo,setAtivo] = useState(null)
  const poeAtivo = (indice) =>{
      if (indice==indice){
          // setInativo(indice)
          
      }
      setAtivo(indice)
      console.log('ativandooo')
  }

    return (

<body className={styles.estrutura}>
      <Head>
        <title>Quick Galetos</title>
        {/* <meta name="Sítio do café" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, cardápio galeto opções pratos" />
      </Head>


      <Cabecalho funcao={mudaRenderiza}/>
    
      
      <div className={styles.corpo_cardapio}>
      <button  className={styles.botao} onClick={posiciona}>CLICA CLICA</button>
      <NavCardapio referencia={posicaoElemento} />
     
      <PaginaCardapio key={1}  conteudo={conteudo}  pagina={1} posicao_a={1} posicao_b={10} titulo='Carnes' estaAtivo={estaAtivo} poeAtivo={poeAtivo} />
      <PaginaCardapio ref={posicaoElemento} key={2} conteudo={conteudo}  pagina={2} posicao_a={12} posicao_b={28} titulo='Vegetais' estaAtivo={estaAtivo} poeAtivo={poeAtivo} />
      <PaginaCardapio key={3} conteudo={conteudo}  pagina={3} posicao_a={12} posicao_b={28} titulo='Vegetais' estaAtivo={estaAtivo} poeAtivo={poeAtivo} />
      <PaginaCardapio key={4} conteudo={conteudo}  pagina={4} posicao_a={12} posicao_b={28} titulo='Vegetais' estaAtivo={estaAtivo} poeAtivo={poeAtivo} />
      <PaginaCardapio key={5} conteudo={conteudo} pagina={5} posicao_a={12} posicao_b={28} titulo='Vegetais' estaAtivo={estaAtivo} poeAtivo={poeAtivo} />
      {/* <PaginaCardapio conteudo={conteudo} pagina={2}  /> */}
      </div>
        
      {/* <IMGFundo /> */}
      <Rodape />


    </body>



    //    {/* <Conteudo_Cardapio Cardapio={conteudo.Cardapio} posicao={0} /> */}

    );
  };
  
