// import styles from '../styles/Home.module.css'
import styles from '../styles/layout.module.css'
import Head from 'next/head'



import Cabecalho_Cardapio from './layout/Cabecalho_Cardapio';

import { useRef } from 'react';
import { useState } from 'react';
export default function Cardapio({ conteudo,mudaRenderiza }) {


    return (

<body className={styles.estrutura}>
      <Head>
        <title>Quick Galetos</title>
        {/* <meta name="Sítio do café" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, cardápio galeto opções pratos" />
      </Head>


      <Cabecalho funcao={mudaRenderiza}/>
    
      
      <div  className={styles.corpo} >


      </div >
        
      {/* <IMGFundo /> */}
      <Rodape />


    </body>



    //    {/* <Conteudo_Cardapio Cardapio={conteudo.Cardapio} posicao={0} /> */}

    );
  };
  
