// import styles from '../styles/Home.module.css'
import styles from '../styles/layout.module.css'
import Head from 'next/head'



import Cabecalho from './layout/Cabecalho';
import Rodape from './layout/Rodape';
import TextoEntregas from './Componentes/TextoEntregas';
import TextoEntregas_b from './Componentes/TextoEntregas_b';
import { useRef } from 'react';
import { useState } from 'react';
export default function Cardapio({ conteudo,mudaRenderiza }) {


  const horarios =[' das 12 às 17h',' das 12 às 22h',' das 12 às 20h',]
  const textos = ['Fazemos entregas em Copacabana, Ipanema, Botafogo, Humaitá e Urca','Nosso horário de entrega é:' ]
  const textos_2 = ['Contatos','Nosso horário de entrega é:' ]
  // const texto


    return (

<body className={styles.estrutura}>
      <Head>
        <title>Quick Galetos</title>
        {/* <meta name="Sítio do café" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, cardápio galeto opções pratos" />
      </Head>


      <Cabecalho funcao={mudaRenderiza}/>
    
      
      <div  className={styles.corpo_entregas} >
      <TextoEntregas texto={['ababa']}/>
      <TextoEntregas_b texto={['ababa']}/>
      </div >
        
      {/*  */}
      <Rodape />


    </body>



    //    {/* <Conteudo_Cardapio Cardapio={conteudo.Cardapio} posicao={0} /> */}

    );
  };
  
