import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import styles from '../styles/layout.module.css'


// import Explicacao from './Componentes/Explicacao';

import Cabecalho from './layout/Cabecalho';
import IMGFundo from './layout/IMGFundo';

import Rodape from './layout/Rodape';
import Carrossel from './Arranjos/Carrossel';
import Comidas from './Arranjos/Comidas';

import { useState } from 'react';
import Cardapio from './Cardapio';




export default function Home({ conteudo }) {


  

  const [renderiza, setRenderiza] = useState('inicio')
  // renderizaDimensao = 

  function mudaRenderiza (pagina)  {
        
        // if (renderiza == 'inicio') {
              setRenderiza(pagina)
              console.log('função liga',pagina)
        // } else {
        //    setRenderiza('inicio')
        // console.log('função  desliga') }
        
  }


  // console.log(conteudo);

  if (renderiza=='inicio') {
    return (
      <div className={styles.estrutura}>
        <Head>
          <title>Quick Galetos</title>
          {/* <meta name="Sítio do café" content="Generated by create next app" /> */}
          <link rel="icon" href="/favicon.ico" />
          <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width" />
        </Head>
  
  
        <Cabecalho funcao={mudaRenderiza}/>
  
        <div className={styles.corpo}>
          <Carrossel conteudo={conteudo} />
          <Comidas/>
        </div>
        {/* <div className={styles.div_espaço}></div> */}
  
  
        <IMGFundo />
        <Rodape />
  
  
      </div>
    )
  }
  if (renderiza=='cardapio') {
    // return   <div>dasdasd</div>
    
    return  <Cardapio conteudo={conteudo} mudaRenderiza={mudaRenderiza}>fsdfsd</Cardapio>
  }


}
