import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import styles from '../styles/layout.module.css'


// import Explicacao from './Componentes/Explicacao';

import Cabecalho from './layout/Cabecalho';
import IMGFundo from './layout/IMGFundo';
import Corpo from './layout/Corpo';
import Rodape from './layout/Rodape';



export default function Home({conteudo}) {
    console.log(conteudo);
  return (
    <div className={styles.estrutura}>
      <Head>
        <title>Sitio do Café</title>
        {/* <meta name="Sítio do café" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
        <meta  name="viewport"  content="minimum-scale=1, initial-scale=1, width=device-width"/>
      </Head>

            
      <Cabecalho />
      
      <Corpo conteudo={conteudo}/>
            {/* <div className={styles.div_espaço}></div> */}
    
      
            <IMGFundo/>
      <Rodape/>
       
    
    </div>
  )
}

